name: Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ # Usa a Action local
        with:
          cypress-command: 'run'
          spec-pattern: 'cypress/e2e/*.spec.js'
          browser: 'chrome'
          record: 'true' # Se você quiser gravar no Cypress Dashboard
          record-key: ${{ secrets.CYPRESS_RECORD_KEY }} # Armazene sua chave como um secret
